export const SCHEMA_REFS = {
  Project:
    "https://schemas.cinematic-story-studio.dev/v1/project.schema.json",
  ImportedStory:
    "https://schemas.cinematic-story-studio.dev/v1/imported-story.schema.json",
  SourceDocument:
    "https://schemas.cinematic-story-studio.dev/v1/source-document.schema.json",
  Chapter:
    "https://schemas.cinematic-story-studio.dev/v1/chapter.schema.json",
  Scene: "https://schemas.cinematic-story-studio.dev/v1/scene.schema.json",
  StoryBeat:
    "https://schemas.cinematic-story-studio.dev/v1/story-beat.schema.json",
  Character:
    "https://schemas.cinematic-story-studio.dev/v1/character.schema.json",
  DialogueLine:
    "https://schemas.cinematic-story-studio.dev/v1/dialogue-line.schema.json",
  DialogueAttribution:
    "https://schemas.cinematic-story-studio.dev/v1/dialogue-attribution.schema.json",
  VoiceProfile:
    "https://schemas.cinematic-story-studio.dev/v1/voice-profile.schema.json",
  CastingAssignment:
    "https://schemas.cinematic-story-studio.dev/v1/casting-assignment.schema.json",
  PerformanceDirection:
    "https://schemas.cinematic-story-studio.dev/v1/performance-direction.schema.json",
  AmbienceCue:
    "https://schemas.cinematic-story-studio.dev/v1/ambience-cue.schema.json",
  FoleyCue:
    "https://schemas.cinematic-story-studio.dev/v1/foley-cue.schema.json",
  MusicCue:
    "https://schemas.cinematic-story-studio.dev/v1/music-cue.schema.json",
  ProductionTimeline:
    "https://schemas.cinematic-story-studio.dev/v1/production-timeline.schema.json",
  ContinuityRecord:
    "https://schemas.cinematic-story-studio.dev/v1/continuity-record.schema.json",
  RenderJob:
    "https://schemas.cinematic-story-studio.dev/v1/render-job.schema.json",
  RenderManifest:
    "https://schemas.cinematic-story-studio.dev/v1/render-manifest.schema.json",
  QualityControlFinding:
    "https://schemas.cinematic-story-studio.dev/v1/quality-control-finding.schema.json",
  ApprovalDecision:
    "https://schemas.cinematic-story-studio.dev/v1/approval-decision.schema.json",
  RuntimeAgentDefinition:
    "https://schemas.cinematic-story-studio.dev/v1/runtime-agent-definition.schema.json",
  AgentExecutionEnvelope:
    "https://schemas.cinematic-story-studio.dev/v1/agent-execution-envelope.schema.json",
  AnalysisProfile:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-profile.schema.json",
  StoryAnalysisRun:
    "https://schemas.cinematic-story-studio.dev/v2/story-analysis-run.schema.json",
  AnalysisAgentExecution:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-agent-execution.schema.json",
  AnalysisSnapshot:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-snapshot.schema.json",
  StoryStructure:
    "https://schemas.cinematic-story-studio.dev/v2/story-structure.schema.json",
  AnalysisChapter:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-chapter.schema.json",
  AnalysisScene:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-scene.schema.json",
  AnalysisBeat:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-beat.schema.json",
  CharacterIdentity:
    "https://schemas.cinematic-story-studio.dev/v2/character-identity.schema.json",
  CharacterAlias:
    "https://schemas.cinematic-story-studio.dev/v2/character-alias.schema.json",
  CharacterMention:
    "https://schemas.cinematic-story-studio.dev/v2/character-mention.schema.json",
  AnalysisDialogueLine:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-dialogue-line.schema.json",
  DialogueAttributionCandidate:
    "https://schemas.cinematic-story-studio.dev/v2/dialogue-attribution-candidate.schema.json",
  EffectiveDialogueAttribution:
    "https://schemas.cinematic-story-studio.dev/v2/effective-dialogue-attribution.schema.json",
  NarrationSpan:
    "https://schemas.cinematic-story-studio.dev/v2/narration-span.schema.json",
  PovSegment:
    "https://schemas.cinematic-story-studio.dev/v2/pov-segment.schema.json",
  StoryLocation:
    "https://schemas.cinematic-story-studio.dev/v2/story-location.schema.json",
  TimelineEvent:
    "https://schemas.cinematic-story-studio.dev/v2/timeline-event.schema.json",
  TemporalConstraint:
    "https://schemas.cinematic-story-studio.dev/v2/temporal-constraint.schema.json",
  CharacterRelationship:
    "https://schemas.cinematic-story-studio.dev/v2/character-relationship.schema.json",
  EmotionalState:
    "https://schemas.cinematic-story-studio.dev/v2/emotional-state.schema.json",
  DramaticIntent:
    "https://schemas.cinematic-story-studio.dev/v2/dramatic-intent.schema.json",
  ContinuityFinding:
    "https://schemas.cinematic-story-studio.dev/v2/continuity-finding.schema.json",
  AnalysisEvidenceSpan:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-evidence-span.schema.json",
  AnalysisConfidence:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-confidence.schema.json",
  AnalysisWarning:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-warning.schema.json",
  AnalysisProvenance:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-provenance.schema.json",
  CreateAnalysisCorrectionRequest:
    "https://schemas.cinematic-story-studio.dev/v2/create-analysis-correction-request.schema.json",
  AnalysisCorrection:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-correction.schema.json",
  AnalysisGateReview:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-gate-review.schema.json",
  AnalysisGateDecision:
    "https://schemas.cinematic-story-studio.dev/v2/analysis-gate-decision.schema.json",
  Phase2BuildEvidenceManifest:
    "https://schemas.cinematic-story-studio.dev/v2/phase-2-build-evidence-manifest.schema.json",
  Phase2PackagedE2eResult:
    "https://schemas.cinematic-story-studio.dev/v2/phase-2-packaged-e2e-result.schema.json",
  VoiceProviderDescriptor:
    "https://schemas.cinematic-story-studio.dev/v3/voice-provider-descriptor.schema.json",
  VoiceModelDescriptor:
    "https://schemas.cinematic-story-studio.dev/v3/voice-model-descriptor.schema.json",
  VoiceCapability:
    "https://schemas.cinematic-story-studio.dev/v3/voice-capability.schema.json",
  VoiceCatalogRevision:
    "https://schemas.cinematic-story-studio.dev/v3/voice-catalog-revision.schema.json",
  CastingVoiceProfile:
    "https://schemas.cinematic-story-studio.dev/v3/casting-voice-profile.schema.json",
  VoiceRightsRecord:
    "https://schemas.cinematic-story-studio.dev/v3/voice-rights-record.schema.json",
  ProductionRole:
    "https://schemas.cinematic-story-studio.dev/v3/production-role.schema.json",
  NarratorRole:
    "https://schemas.cinematic-story-studio.dev/v3/narrator-role.schema.json",
  CharacterVoiceRole:
    "https://schemas.cinematic-story-studio.dev/v3/character-voice-role.schema.json",
  CustomProductionRole:
    "https://schemas.cinematic-story-studio.dev/v3/custom-production-role.schema.json",
  CastingProfile:
    "https://schemas.cinematic-story-studio.dev/v3/casting-profile.schema.json",
  CastingRun:
    "https://schemas.cinematic-story-studio.dev/v3/casting-run.schema.json",
  CastingCandidate:
    "https://schemas.cinematic-story-studio.dev/v3/casting-candidate.schema.json",
  CastingCompatibilityAssessment:
    "https://schemas.cinematic-story-studio.dev/v3/casting-compatibility-assessment.schema.json",
  CastingConflict:
    "https://schemas.cinematic-story-studio.dev/v3/casting-conflict.schema.json",
  CastAssignment:
    "https://schemas.cinematic-story-studio.dev/v3/cast-assignment.schema.json",
  CastingCorrection:
    "https://schemas.cinematic-story-studio.dev/v3/casting-correction.schema.json",
  CastingGateReview:
    "https://schemas.cinematic-story-studio.dev/v3/casting-gate-review.schema.json",
  CastingReviewDecision:
    "https://schemas.cinematic-story-studio.dev/v3/casting-review-decision.schema.json",
  ApprovedCastSnapshot:
    "https://schemas.cinematic-story-studio.dev/v3/approved-cast-snapshot.schema.json",
  SyntheticVoiceCatalog:
    "https://schemas.cinematic-story-studio.dev/v3/synthetic-voice-catalog.schema.json",
  Phase3PackagedE2eResult:
    "https://schemas.cinematic-story-studio.dev/v3/phase-3-packaged-e2e-result.schema.json",
  Phase3BuildEvidenceManifest:
    "https://schemas.cinematic-story-studio.dev/v3/phase-3-build-evidence-manifest.schema.json"
} as const;

export type PublicSchemaName = keyof typeof SCHEMA_REFS;
